[static_config]
# For default USER_AGENT header value in reqwest client headers
contact = "none"

# Where to store runtime config (local to home)
dynamic_config_path = "~/.config/mcserver"

[default_dynamic_config]

# The default arguments passed to the java command when the jar is ran
default_java_args = ""

# Whether to use enable nogui when starting the server
nogui = false

# The directory where servers are stored and expected to be stored (local to home)
servers_directory = "~/Servers"

# The default server to be deployed or stopped when the cli is used
# default_server = "my-server"

# Rcon configuration for each server
[default_dynamic_config.rcon]
# my-server = { server_address = "localhost", port = 25575, password = "abc" }

# Equally, you can do mcron.<server> and customize each field line by line
# [default_dynamic_config.rcon.my-second-server]
# server_address = "localhost"
# port = 25575
# password = "abc"

